### ISSUE TITLE
Deploy kardo ji...hame dekhna hai

### ISSUE THREAD

**Issue by omnagare9975** [TejasMore477/My-Portfolio#1]
Use Heroku

**Comment by TejasMore477** [comment]
are bhai developing stage madhi ahe , deploy karayla sangtoo na bhai....ya weles  www vr deploy karnar ahe bhai...

**Comment by omnagare9975** [comment]
Muze dockerfile banane hai

**Comment by TejasMore477** [comment]
is the issue cleared😁
